services:

  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - client
      - backend

  backend:
    image: rabye19/todo-backend:latest
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    depends_on:
      mysql:
        condition: service_healthy
    develop:
      watch:
        - path: ./backend/src
          action: sync
          target: /usr/local/app/src
        - path: ./backend/package.json
          action: rebuild
    labels:
      - "traefik.http.routers.backend.rule=(Host(`localhost`) || Host(`192.168.1.135`)) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"

  client:
    image: rabye19/todo-frontend:latest
    develop:
      watch:
        - path: ./client/src
          action: sync
          target: /usr/local/app/src
        - path: ./client/package.json
          action: rebuild
    labels:
      - "traefik.http.routers.client.rule=Host(`localhost`) || Host(`192.168.1.135`)"
      - "traefik.http.services.client.loadbalancer.server.port=5173"

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    labels:
      - "traefik.http.routers.prometheus.rule=(Host(`localhost`) || Host(`192.168.1.135`)) && PathPrefix(`/prometheus`)"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SERVER_ROOT_URL: http://192.168.1.135/grafana
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    labels:
      - "traefik.http.routers.grafana.rule=(Host(`localhost`) || Host(`192.168.1.135`)) && PathPrefix(`/grafana`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
volumes:
  todo-mysql-data:
  prometheus-data:
  grafana-data:
