name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to server
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Copy compose.yml and .env
        run: |
          cp compose.yml ~/todo-app/compose.yml
          cp prometheus.yml ~/todo-app/prometheus.yml

      - name: Deploy with Docker Compose
        run: |
          cd ~/todo-app
          docker compose pull
          docker compose up -d --remove-orphans

      - name: Verify deployment
        run: |
          cd ~/todo-app
          docker compose ps
